AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for GLiNER ONNX Benchmark Environment'

Parameters:
  InstanceType:
    Type: String
    Default: g4dn.xlarge
    AllowedValues:
      - g4dn.xlarge
      - g4dn.2xlarge
      - c6i.xlarge
      - c6i.2xlarge
      - t3.medium
    Description: 'EC2 instance type. Use g4dn for GPU (CUDA) testing.'

  KeyName:
    Type: String
    Default: "NONE"
    Description: '(Optional) Name of an existing EC2 KeyPair. Keep as "NONE" to use Session Manager (no key needed).'

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/deeplearning/ami/ubuntu-22.04/latest/image_id'
    Description: 'AWS Deep Learning AMI (Ubuntu 22.04) - Pre-installed with NVIDIA drivers and CUDA.'

  SpotPrice:
    Type: String
    Default: "0.20"
    Description: 'Maximum hourly price for the Spot instance. If set to a number, the instance will be launched as a Spot instance to save up to 90%.'

Conditions:
  HasKey: !Not [ !Equals [ !Ref KeyName, "NONE" ] ]

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: gliner-benchmark-vpc

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'

  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: gliner-benchmark-public-subnet

  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC

  DefaultPublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

  GlinerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref InstanceRole

  BenchmarkInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      KeyName: !If [HasKey, !Ref KeyName, !Ref AWS::NoValue]
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref GlinerSecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      InstanceMarketOptions:
        MarketType: spot
        SpotOptions:
          MaxPrice: !Ref SpotPrice
          SpotInstanceType: one-time
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 40
            VolumeType: gp3
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Log output
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          
          echo "Starting GLiNER benchmark setup (Ubuntu)..."
          
          # Update and install basic dependencies
          apt-get update -y
          apt-get install -y git python3-pip python3-venv pciutils
          
          # Clone the repository
          cd /home/ubuntu
          git clone https://github.com/sarinregmi/gliner-onnx.git
          cd gliner-onnx
          
          # Setup virtual environment
          python3 -m venv venv --system-site-packages
          source venv/bin/activate
          
          # Install requirements
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # If it's a GPU instance, ensure onnxruntime-gpu is installed
          if lspci | grep -i nvidia; then
             echo "NVIDIA GPU detected, ensuring onnxruntime-gpu is present"
             pip install onnxruntime-gpu
          fi
          
          # Run the model conversion to generate ONNX files locally 
          python3 convert_model.py
          
          # Final instructions for the user
          echo "Setup complete! You can now run the benchmark:" > /home/ubuntu/README.txt
          echo "cd /home/ubuntu/gliner-onnx" >> /home/ubuntu/README.txt
          echo "source venv/bin/activate" >> /home/ubuntu/README.txt
          echo "python3 benchmark.py" >> /home/ubuntu/README.txt
          
          # Create a refresh script to update code without recreating stack
          cat <<EOF > /home/ubuntu/update_and_run.sh
          #!/bin/bash
          echo "Updating code from GitHub..."
          cd /home/ubuntu/gliner-onnx
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          echo "Running benchmark..."
          python3 benchmark.py
          EOF
          chmod +x /home/ec2-user/update_and_run.sh
          
          chown -R ec2-user:ec2-user /home/ec2-user/gliner-onnx /home/ec2-user/README.txt /home/ec2-user/update_and_run.sh
          echo "✓ All done!"

Outputs:
  InstancePublicIp:
    Description: 'Public IP of the benchmark instance'
    Value: !GetAtt BenchmarkInstance.PublicIp
  SSHCommand:
    Condition: HasKey
    Description: 'SSH command to connect (only if KeyPair provided)'
    Value: !Sub 'ssh -i YourKeyPair.pem ubuntu@${BenchmarkInstance.PublicIp}'
  SessionManagerLink:
    Description: 'Link to connect via Session Manager (Recommended)'
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/systems-manager/session-manager/${BenchmarkInstance.InstanceId}'
